//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perenthia.Web.Services.Security {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Security.IAuth")]
    public interface IAuth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Authenticate", ReplyAction="http://tempuri.org/IAuth/AuthenticateResponse")]
        Lionsguard.Security.Gamer Authenticate(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Create", ReplyAction="http://tempuri.org/IAuth/CreateResponse")]
        Lionsguard.Security.Gamer Create(string username, string displayName, string password, string email, string birthDate, string securityQuestion, string securityAnswer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IAuthChannel : Perenthia.Web.Services.Security.IAuth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AuthClient : System.ServiceModel.ClientBase<Perenthia.Web.Services.Security.IAuth>, Perenthia.Web.Services.Security.IAuth {
        
        public AuthClient() {
        }
        
        public AuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Lionsguard.Security.Gamer Authenticate(string username, string password) {
            return base.Channel.Authenticate(username, password);
        }
        
        public Lionsguard.Security.Gamer Create(string username, string displayName, string password, string email, string birthDate, string securityQuestion, string securityAnswer) {
            return base.Channel.Create(username, displayName, password, email, birthDate, securityQuestion, securityAnswer);
        }
    }
}
