//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radiance.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radiance.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to execute the {0} command..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number or types of arguments supplied to the command are invalid..
        /// </summary>
        internal static string ArgsInvalid {
            get {
                return ResourceManager.GetString("ArgsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attempts to attack but misses..
        /// </summary>
        internal static string AttackAttackerFailed {
            get {
                return ResourceManager.GetString("AttackAttackerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your attack was unsuccessful..
        /// </summary>
        internal static string AttackFailed {
            get {
                return ResourceManager.GetString("AttackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were hit by {0} for {1} points of damage..
        /// </summary>
        internal static string AttackHitByAttacker {
            get {
                return ResourceManager.GetString("AttackHitByAttacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hit {0} for {1} points of damage..
        /// </summary>
        internal static string AttackHitDefender {
            get {
                return ResourceManager.GetString("AttackHitDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your attack fails and you missed your target!.
        /// </summary>
        internal static string AttackMiss {
            get {
                return ResourceManager.GetString("AttackMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target is out of range..
        /// </summary>
        internal static string AttackOutOfRange {
            get {
                return ResourceManager.GetString("AttackOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been knocked unconscious..
        /// </summary>
        internal static string AttackUnconsciousDefender {
            get {
                return ResourceManager.GetString("AttackUnconsciousDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been knocked unconscious..
        /// </summary>
        internal static string AttackYouAreUnconscious {
            get {
                return ResourceManager.GetString("AttackYouAreUnconscious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You killed {0}..
        /// </summary>
        internal static string AttackYouKilledDefender {
            get {
                return ResourceManager.GetString("AttackYouKilledDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were killed by {0}..
        /// </summary>
        internal static string AttackYouWereKilledByAttacker {
            get {
                return ResourceManager.GetString("AttackYouWereKilledByAttacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} has been decreased by {1}..
        /// </summary>
        internal static string AttributeAffectedDecreased {
            get {
                return ResourceManager.GetString("AttributeAffectedDecreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} has been increased by {1}..
        /// </summary>
        internal static string AttributeAffectedIncreased {
            get {
                return ResourceManager.GetString("AttributeAffectedIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} returns to normal..
        /// </summary>
        internal static string AttributeFaded {
            get {
                return ResourceManager.GetString("AttributeFaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this service..
        /// </summary>
        internal static string AuthorizationFailed {
            get {
                return ResourceManager.GetString("AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell backfired!.
        /// </summary>
        internal static string CastBackfired {
            get {
                return ResourceManager.GetString("CastBackfired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were killed by your own spell!.
        /// </summary>
        internal static string CastBackfiredKilledCaster {
            get {
                return ResourceManager.GetString("CastBackfiredKilledCaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been knocked unconscious by your own spell!.
        /// </summary>
        internal static string CastBackfiredUnconsciousCaster {
            get {
                return ResourceManager.GetString("CastBackfiredUnconsciousCaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your channeling is affecting your health..
        /// </summary>
        internal static string CastChanneling {
            get {
                return ResourceManager.GetString("CastChanneling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has done {0} damage to {1}!.
        /// </summary>
        internal static string CastDamageTarget {
            get {
                return ResourceManager.GetString("CastDamageTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has destroyed {0}..
        /// </summary>
        internal static string CastDestroyedObject {
            get {
                return ResourceManager.GetString("CastDestroyedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attempts to cast a spell on you but the spell fizzles out with no effect..
        /// </summary>
        internal static string CasterCastFailed {
            get {
                return ResourceManager.GetString("CasterCastFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell fizzles out with no effect..
        /// </summary>
        internal static string CastFailed {
            get {
                return ResourceManager.GetString("CastFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has healed {0} damage..
        /// </summary>
        internal static string CastHealSelf {
            get {
                return ResourceManager.GetString("CastHealSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has healed {0} for {1} damage..
        /// </summary>
        internal static string CastHealTarget {
            get {
                return ResourceManager.GetString("CastHealTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has killed {0}!.
        /// </summary>
        internal static string CastKilledTarget {
            get {
                return ResourceManager.GetString("CastKilledTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has no affect on {0}..
        /// </summary>
        internal static string CastNoAffect {
            get {
                return ResourceManager.GetString("CastNoAffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not cast an offensive spell on yourself!.
        /// </summary>
        internal static string CastNotSelf {
            get {
                return ResourceManager.GetString("CastNotSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Protection has increased by {0}..
        /// </summary>
        internal static string CastSelfBuff {
            get {
                return ResourceManager.GetString("CastSelfBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully cast {0} on {1}..
        /// </summary>
        internal static string CastSuccess {
            get {
                return ResourceManager.GetString("CastSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Protection has been increased by {1}..
        /// </summary>
        internal static string CastTargetBuff {
            get {
                return ResourceManager.GetString("CastTargetBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were hit for {0} damage by {1}!.
        /// </summary>
        internal static string CastTargetDamaged {
            get {
                return ResourceManager.GetString("CastTargetDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been healed for {0} damage by {1}..
        /// </summary>
        internal static string CastTargetHealed {
            get {
                return ResourceManager.GetString("CastTargetHealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were killed by {0}..
        /// </summary>
        internal static string CastTargetKilled {
            get {
                return ResourceManager.GetString("CastTargetKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were rendered unconscious by {0}..
        /// </summary>
        internal static string CastTargetUnconscious {
            get {
                return ResourceManager.GetString("CastTargetUnconscious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has rendered {0} unconscious..
        /// </summary>
        internal static string CastUnconsciousTarget {
            get {
                return ResourceManager.GetString("CastUnconsciousTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default CryptographyProvider not found in application configuration file..
        /// </summary>
        internal static string ConfigDefaultCryptoProviderNotFound {
            get {
                return ResourceManager.GetString("ConfigDefaultCryptoProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default LogProvider not found in application configuration file..
        /// </summary>
        internal static string ConfigDefaultLogProviderNotFound {
            get {
                return ResourceManager.GetString("ConfigDefaultLogProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default WorldProvider not found in application configuration file..
        /// </summary>
        internal static string ConfigDefaultWorldProviderNotFound {
            get {
                return ResourceManager.GetString("ConfigDefaultWorldProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;radiance&apos; section of the application configuration file was not found..
        /// </summary>
        internal static string ConfigRadianceSectionNotFound {
            get {
                return ResourceManager.GetString("ConfigRadianceSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A world configuration file was not found for the current virtual world..
        /// </summary>
        internal static string ConfigWorldFileNotFound {
            get {
                return ResourceManager.GetString("ConfigWorldFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of {0} failed to be initialized from the world configuration file..
        /// </summary>
        internal static string ConfigWorldNotCreated {
            get {
                return ResourceManager.GetString("ConfigWorldNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of the world type specified in the radiance section of the application configuration file could not be created. wordType = {0}.
        /// </summary>
        internal static string ConfigWorldTypeNotFound {
            get {
                return ResourceManager.GetString("ConfigWorldTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} attribute does not contain a valid value..
        /// </summary>
        internal static string CreateCharacterAttributeOutOfRange {
            get {
                return ResourceManager.GetString("CreateCharacterAttributeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid number of values was specified for the attributes of the new Character..
        /// </summary>
        internal static string CreateCharacterAttributePointsOverLimit {
            get {
                return ResourceManager.GetString("CreateCharacterAttributePointsOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A gender was not specified for the new Character..
        /// </summary>
        internal static string CreateCharacterInvalidGender {
            get {
                return ResourceManager.GetString("CreateCharacterInvalidGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A race was not specified for the new Character..
        /// </summary>
        internal static string CreateCharacterInvalidRace {
            get {
                return ResourceManager.GetString("CreateCharacterInvalidRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must login before attempt to create a new Character..
        /// </summary>
        internal static string CreateCharacterInvalidUser {
            get {
                return ResourceManager.GetString("CreateCharacterInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already created the maximum number of Characters ({0}). In order to create additional Characters you will need to purchase them with Emblem..
        /// </summary>
        internal static string CreateCharacterMaxExceeded {
            get {
                return ResourceManager.GetString("CreateCharacterMaxExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} skill does not contain a valid value..
        /// </summary>
        internal static string CreateCharacterSkillOutOfRange {
            get {
                return ResourceManager.GetString("CreateCharacterSkillOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid number of values was specified for the skills of the new Character..
        /// </summary>
        internal static string CreateCharacterSkillPointsOverLimit {
            get {
                return ResourceManager.GetString("CreateCharacterSkillPointsOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character was successfully created..
        /// </summary>
        internal static string CreateCharacterSuccess {
            get {
                return ResourceManager.GetString("CreateCharacterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error has occurred on the server. Your command was not executed, technical support has been notified of the issue..
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Command.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is required to access this service..
        /// </summary>
        internal static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} says: {1}.
        /// </summary>
        internal static string MsgSayFormat {
            get {
                return ResourceManager.GetString("MsgSayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You say: {0}.
        /// </summary>
        internal static string MsgSayFormatEcho {
            get {
                return ResourceManager.GetString("MsgSayFormatEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} shouts: {1}.
        /// </summary>
        internal static string MsgShoutFormat {
            get {
                return ResourceManager.GetString("MsgShoutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You shout: {0}.
        /// </summary>
        internal static string MsgShoutFormatEcho {
            get {
                return ResourceManager.GetString("MsgShoutFormatEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tells you: {1}.
        /// </summary>
        internal static string MsgTellFormat {
            get {
                return ResourceManager.GetString("MsgTellFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tell {0}: {1}.
        /// </summary>
        internal static string MsgTellFormatEcho {
            get {
                return ResourceManager.GetString("MsgTellFormatEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell requires the name of the person you wish to speak with..
        /// </summary>
        internal static string MsgTellNoAvatarDefined {
            get {
                return ResourceManager.GetString("MsgTellNoAvatarDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not seem to be online..
        /// </summary>
        internal static string MsgTellNotFound {
            get {
                return ResourceManager.GetString("MsgTellNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not contain spaces, numbers or special characters such as $@!#..
        /// </summary>
        internal static string NameValidationInvalidCharacters {
            get {
                return ResourceManager.GetString("NameValidationInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be greater than 32 characters in length..
        /// </summary>
        internal static string NameValidationInvalidLengthLong {
            get {
                return ResourceManager.GetString("NameValidationInvalidLengthLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name be at least 3 characters in length..
        /// </summary>
        internal static string NameValidationInvalidLengthShort {
            get {
                return ResourceManager.GetString("NameValidationInvalidLengthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name specified is not allowed..
        /// </summary>
        internal static string NameValidationInvalidName {
            get {
                return ResourceManager.GetString("NameValidationInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name chosen already exists..
        /// </summary>
        internal static string NameValidationNameAlreadyExists {
            get {
                return ResourceManager.GetString("NameValidationNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enters from the {1}..
        /// </summary>
        internal static string PlaceAvatarEnter {
            get {
                return ResourceManager.GetString("PlaceAvatarEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exits to the {1}..
        /// </summary>
        internal static string PlaceAvatarExit {
            get {
                return ResourceManager.GetString("PlaceAvatarExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your skill in {0} has increased to {1}..
        /// </summary>
        internal static string SkillAdvanced {
            get {
                return ResourceManager.GetString("SkillAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently offline..
        /// </summary>
        internal static string WorldOffline {
            get {
                return ResourceManager.GetString("WorldOffline", resourceCulture);
            }
        }
    }
}
