//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perenthia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Perenthia.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not perform this action on {0}..
        /// </summary>
        internal static string ActionCanNotPerform {
            get {
                return ResourceManager.GetString("ActionCanNotPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Action Slot &apos;{0}&apos;..
        /// </summary>
        internal static string ActionInvalidSlot {
            get {
                return ResourceManager.GetString("ActionInvalidSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action {0} reset..
        /// </summary>
        internal static string ActionReset {
            get {
                return ResourceManager.GetString("ActionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action {0} set to {1}..
        /// </summary>
        internal static string ActionSet {
            get {
                return ResourceManager.GetString("ActionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor was not created..
        /// </summary>
        internal static string ActorNotCreated {
            get {
                return ResourceManager.GetString("ActorNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object with an ID/Alias of &apos;{0}&apos; could not be located..
        /// </summary>
        internal static string ActorNotFound {
            get {
                return ResourceManager.GetString("ActorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor was not saved..
        /// </summary>
        internal static string ActorNotSaved {
            get {
                return ResourceManager.GetString("ActorNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTOR SAVED.
        /// </summary>
        internal static string AdminActorSaved {
            get {
                return ResourceManager.GetString("AdminActorSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTERING ADMIN BUILD MODE.
        /// </summary>
        internal static string AdminEnterBuildMode {
            get {
                return ResourceManager.GetString("AdminEnterBuildMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your actions have earned you the {0}!.
        /// </summary>
        internal static string AwardGained {
            get {
                return ResourceManager.GetString("AwardGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not afford {0}..
        /// </summary>
        internal static string CanNotAfford {
            get {
                return ResourceManager.GetString("CanNotAfford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently targeting yourself, choose another target to attack..
        /// </summary>
        internal static string CanNotAttackSelf {
            get {
                return ResourceManager.GetString("CanNotAttackSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not drop that here..
        /// </summary>
        internal static string CanNotDrop {
            get {
                return ResourceManager.GetString("CanNotDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not equip {0}, you do not have enough container slots open to equip it..
        /// </summary>
        internal static string CanNotEquipMoreBags {
            get {
                return ResourceManager.GetString("CanNotEquipMoreBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not get {0}..
        /// </summary>
        internal static string CanNotGet {
            get {
                return ResourceManager.GetString("CanNotGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not purchase this item because your inventory is full..
        /// </summary>
        internal static string CanNotPurchaseInventoryFull {
            get {
                return ResourceManager.GetString("CanNotPurchaseInventoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to use a different skill in order to speak to the dead..
        /// </summary>
        internal static string CanNotSpeakToDead {
            get {
                return ResourceManager.GetString("CanNotSpeakToDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not target something that is not within the same room as you..
        /// </summary>
        internal static string CanNotTargetNotInPlace {
            get {
                return ResourceManager.GetString("CanNotTargetNotInPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is full and can not be unequipped. Remove the contents before attempting to unequip..
        /// </summary>
        internal static string CanNotUnequipBag {
            get {
                return ResourceManager.GetString("CanNotUnequipBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use {0} while frozen!.
        /// </summary>
        internal static string CanNotUseWhileFrozen {
            get {
                return ResourceManager.GetString("CanNotUseWhileFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not use {0} while stunned..
        /// </summary>
        internal static string CanNotUseWhileStunned {
            get {
                return ResourceManager.GetString("CanNotUseWhileStunned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not view the goods of an NPC unless they are present within the same room as you..
        /// </summary>
        internal static string CanNotViewNpcGoodsNotInPlace {
            get {
                return ResourceManager.GetString("CanNotViewNpcGoodsNotInPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not view the inventory of {0}..
        /// </summary>
        internal static string CanNotViewTargetInventory {
            get {
                return ResourceManager.GetString("CanNotViewTargetInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast failed..
        /// </summary>
        internal static string CastFailed {
            get {
                return ResourceManager.GetString("CastFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; command requires the following structure or syntax: {1}.
        /// </summary>
        internal static string CmdSyntax {
            get {
                return ResourceManager.GetString("CmdSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified container &apos;{0}&apos; is full..
        /// </summary>
        internal static string ContainerFull {
            get {
                return ResourceManager.GetString("ContainerFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your attempt to create {0} has failed..
        /// </summary>
        internal static string CraftFailed {
            get {
                return ResourceManager.GetString("CraftFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} required to craft {1}..
        /// </summary>
        internal static string CraftIngredientRequired {
            get {
                return ResourceManager.GetString("CraftIngredientRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any space to place {0}..
        /// </summary>
        internal static string CraftNoSpaceLeft {
            get {
                return ResourceManager.GetString("CraftNoSpaceLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A skill level of {0} is required in {1} in order to craft {2}..
        /// </summary>
        internal static string CraftNotRequiredSkillLevel {
            get {
                return ResourceManager.GetString("CraftNotRequiredSkillLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully created {0}..
        /// </summary>
        internal static string CraftSuccess {
            get {
                return ResourceManager.GetString("CraftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive {0}..
        /// </summary>
        internal static string CurrencyGained {
            get {
                return ResourceManager.GetString("CurrencyGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive {0} Emblem..
        /// </summary>
        internal static string EmblemGained {
            get {
                return ResourceManager.GetString("EmblemGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string Emote {
            get {
                return ResourceManager.GetString("Emote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} begins to cry....
        /// </summary>
        internal static string EmoteCry {
            get {
                return ResourceManager.GetString("EmoteCry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tears begin streaming down your face....
        /// </summary>
        internal static string EmoteCrySelf {
            get {
                return ResourceManager.GetString("EmoteCrySelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} begins to dance around!.
        /// </summary>
        internal static string EmoteDance {
            get {
                return ResourceManager.GetString("EmoteDance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You begin to dance!.
        /// </summary>
        internal static string EmoteDanceSelf {
            get {
                return ResourceManager.GetString("EmoteDanceSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} grins :).
        /// </summary>
        internal static string EmoteGrin {
            get {
                return ResourceManager.GetString("EmoteGrin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You grin :).
        /// </summary>
        internal static string EmoteGrinSelf {
            get {
                return ResourceManager.GetString("EmoteGrinSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} laughs out loud!.
        /// </summary>
        internal static string EmoteLaugh {
            get {
                return ResourceManager.GetString("EmoteLaugh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You laugh out loud!.
        /// </summary>
        internal static string EmoteLaughSelf {
            get {
                return ResourceManager.GetString("EmoteLaughSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You {0}.
        /// </summary>
        internal static string EmoteSelf {
            get {
                return ResourceManager.GetString("EmoteSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} begins to sing..
        /// </summary>
        internal static string EmoteSing {
            get {
                return ResourceManager.GetString("EmoteSing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You begin to sing..
        /// </summary>
        internal static string EmoteSingSelf {
            get {
                return ResourceManager.GetString("EmoteSingSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} smiles..
        /// </summary>
        internal static string EmoteSmile {
            get {
                return ResourceManager.GetString("EmoteSmile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You smile..
        /// </summary>
        internal static string EmoteSmileSelf {
            get {
                return ResourceManager.GetString("EmoteSmileSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} waves..
        /// </summary>
        internal static string EmoteWave {
            get {
                return ResourceManager.GetString("EmoteWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} waves at you..
        /// </summary>
        internal static string EmoteWaveByTarget {
            get {
                return ResourceManager.GetString("EmoteWaveByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You wave..
        /// </summary>
        internal static string EmoteWaveSelf {
            get {
                return ResourceManager.GetString("EmoteWaveSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You wave at {0}..
        /// </summary>
        internal static string EmoteWaveTarget {
            get {
                return ResourceManager.GetString("EmoteWaveTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} winks..
        /// </summary>
        internal static string EmoteWink {
            get {
                return ResourceManager.GetString("EmoteWink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} winks at you..
        /// </summary>
        internal static string EmoteWinkByTarget {
            get {
                return ResourceManager.GetString("EmoteWinkByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You wink..
        /// </summary>
        internal static string EmoteWinkSelf {
            get {
                return ResourceManager.GetString("EmoteWinkSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You wink at {0}..
        /// </summary>
        internal static string EmoteWinkTarget {
            get {
                return ResourceManager.GetString("EmoteWinkTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have gained {0} experience..
        /// </summary>
        internal static string ExperienceGained {
            get {
                return ResourceManager.GetString("ExperienceGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have lost {0} experience..
        /// </summary>
        internal static string ExperienceLost {
            get {
                return ResourceManager.GetString("ExperienceLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perenthia is currently offline..
        /// </summary>
        internal static string GameOffline {
            get {
                return ResourceManager.GetString("GameOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gave {0} to {1}..
        /// </summary>
        internal static string GaveItem {
            get {
                return ResourceManager.GetString("GaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you trying to give this item to?.
        /// </summary>
        internal static string GiveWho {
            get {
                return ResourceManager.GetString("GiveWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You retrieved {0}..
        /// </summary>
        internal static string GotItem {
            get {
                return ResourceManager.GetString("GotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your health has increased by {0}..
        /// </summary>
        internal static string HealthGained {
            get {
                return ResourceManager.GetString("HealthGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your health has decreased by {0}..
        /// </summary>
        internal static string HealthLost {
            get {
                return ResourceManager.GetString("HealthLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avatar-{0}-{1}.png.
        /// </summary>
        internal static string ImgAvatar {
            get {
                return ResourceManager.GetString("ImgAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item-{0}-{1}.png.
        /// </summary>
        internal static string ImgItem {
            get {
                return ResourceManager.GetString("ImgItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order-{0}-128.png.
        /// </summary>
        internal static string ImgOrder {
            get {
                return ResourceManager.GetString("ImgOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your inventory is full!.
        /// </summary>
        internal static string InventoryFull {
            get {
                return ResourceManager.GetString("InventoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough space in your inventory for the requested items..
        /// </summary>
        internal static string InventoryNotEnoughSpace {
            get {
                return ResourceManager.GetString("InventoryNotEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was added to your inventory..
        /// </summary>
        internal static string ItemAdded {
            get {
                return ResourceManager.GetString("ItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} is already equipped..
        /// </summary>
        internal static string ItemAlreadyEquipped {
            get {
                return ResourceManager.GetString("ItemAlreadyEquipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be used..
        /// </summary>
        internal static string ItemCanNotBeUsed {
            get {
                return ResourceManager.GetString("ItemCanNotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not equip {0}..
        /// </summary>
        internal static string ItemCanNotEquip {
            get {
                return ResourceManager.GetString("ItemCanNotEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That item can not be unequipped because you do not currently have a container such as backpack or bag equipped..
        /// </summary>
        internal static string ItemCanNotEquipNoContainer {
            get {
                return ResourceManager.GetString("ItemCanNotEquipNoContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That item can not be equipped because it was not found in your inventory..
        /// </summary>
        internal static string ItemCanNotEquipNotInInventory {
            get {
                return ResourceManager.GetString("ItemCanNotEquipNotInInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not equip {0}, so it stands to reason that you would not be able to un-equip it. :).
        /// </summary>
        internal static string ItemCanNotEquipNoUnequip {
            get {
                return ResourceManager.GetString("ItemCanNotEquipNoUnequip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not purchase {0}..
        /// </summary>
        internal static string ItemCanNotPurchase {
            get {
                return ResourceManager.GetString("ItemCanNotPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not sell {0} to {1}..
        /// </summary>
        internal static string ItemCanNotSell {
            get {
                return ResourceManager.GetString("ItemCanNotSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That item can not be unequipped because it was not found in your equipment..
        /// </summary>
        internal static string ItemCanNotUnequipNotInEquipment {
            get {
                return ResourceManager.GetString("ItemCanNotUnequipNotInEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You create {0}..
        /// </summary>
        internal static string ItemCreated {
            get {
                return ResourceManager.GetString("ItemCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You drop {0}..
        /// </summary>
        internal static string ItemDropped {
            get {
                return ResourceManager.GetString("ItemDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have equipped {0}..
        /// </summary>
        internal static string ItemEquipped {
            get {
                return ResourceManager.GetString("ItemEquipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive {0}..
        /// </summary>
        internal static string ItemGained {
            get {
                return ResourceManager.GetString("ItemGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has increased your health..
        /// </summary>
        internal static string ItemHealthGained {
            get {
                return ResourceManager.GetString("ItemHealthGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has caused a negative affect to your health!.
        /// </summary>
        internal static string ItemHealthLost {
            get {
                return ResourceManager.GetString("ItemHealthLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no affect on you..
        /// </summary>
        internal static string ItemNoAffect {
            get {
                return ResourceManager.GetString("ItemNoAffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &apos;{0}&apos; could not be located..
        /// </summary>
        internal static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You purchased {0}..
        /// </summary>
        internal static string ItemPurchased {
            get {
                return ResourceManager.GetString("ItemPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been removed from your inventory..
        /// </summary>
        internal static string ItemRemoved {
            get {
                return ResourceManager.GetString("ItemRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the skill level required to equip {0}; raise your skill in &apos;{1}&apos; to at least &apos;{2}&apos;..
        /// </summary>
        internal static string ItemSkillLevelRequiredNotMet {
            get {
                return ResourceManager.GetString("ItemSkillLevelRequiredNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items can only be sold to merchant Non-Player Characters (NPCs)..
        /// </summary>
        internal static string ItemsMustBeSoldToNPCs {
            get {
                return ResourceManager.GetString("ItemsMustBeSoldToNPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sold {0}..
        /// </summary>
        internal static string ItemSold {
            get {
                return ResourceManager.GetString("ItemSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unequipped {0}..
        /// </summary>
        internal static string ItemUnequipped {
            get {
                return ResourceManager.GetString("ItemUnequipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has increased your willpower..
        /// </summary>
        internal static string ItemWillpowerGained {
            get {
                return ResourceManager.GetString("ItemWillpowerGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have advanced to level {0}!.
        /// </summary>
        internal static string LevelGained {
            get {
                return ResourceManager.GetString("LevelGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login credentials supplied..
        /// </summary>
        internal static string LoginInvalid {
            get {
                return ResourceManager.GetString("LoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} says: {1}.
        /// </summary>
        internal static string MsgChat {
            get {
                return ResourceManager.GetString("MsgChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} shouts: {1}.
        /// </summary>
        internal static string MsgShout {
            get {
                return ResourceManager.GetString("MsgShout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tells you: {1}.
        /// </summary>
        internal static string MsgTell {
            get {
                return ResourceManager.GetString("MsgTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is available!.
        /// </summary>
        internal static string NameAvailable {
            get {
                return ResourceManager.GetString("NameAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is unavailable for the following reason: {1}.
        /// </summary>
        internal static string NameUnavailable {
            get {
                return ResourceManager.GetString("NameUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough Emblem to purchase this item. Current Emblem: {0}, Item Cost: {1}..
        /// </summary>
        internal static string NotEnoughEmblem {
            get {
                return ResourceManager.GetString("NotEnoughEmblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enters from the {1}..
        /// </summary>
        internal static string PlaceAvatarEnters {
            get {
                return ResourceManager.GetString("PlaceAvatarEnters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exits to the {1}..
        /// </summary>
        internal static string PlaceAvatarExits {
            get {
                return ResourceManager.GetString("PlaceAvatarExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have discovered {0}..
        /// </summary>
        internal static string PlaceDiscovered {
            get {
                return ResourceManager.GetString("PlaceDiscovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have gained {0} experience for your discovery..
        /// </summary>
        internal static string PlaceDiscoveryExperienceGained {
            get {
                return ResourceManager.GetString("PlaceDiscoveryExperienceGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are dead..
        /// </summary>
        internal static string PlayerDead {
            get {
                return ResourceManager.GetString("PlayerDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were killed by {0}..
        /// </summary>
        internal static string PlayerKilled {
            get {
                return ResourceManager.GetString("PlayerKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has advanced to level {1}!.
        /// </summary>
        internal static string PlayerLevelGained {
            get {
                return ResourceManager.GetString("PlayerLevelGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player record not found..
        /// </summary>
        internal static string PlayerNotFound {
            get {
                return ResourceManager.GetString("PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unconscious..
        /// </summary>
        internal static string PlayerUnconscious {
            get {
                return ResourceManager.GetString("PlayerUnconscious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You put {0} into {1}..
        /// </summary>
        internal static string PutItem {
            get {
                return ResourceManager.GetString("PutItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quest &apos;{0}&apos; has been added to your quest log..
        /// </summary>
        internal static string QuestAddedToLog {
            get {
                return ResourceManager.GetString("QuestAddedToLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already completed this quest..
        /// </summary>
        internal static string QuestAlreadyComplete {
            get {
                return ResourceManager.GetString("QuestAlreadyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed the &apos;{0}&apos; quest. Your quest log has been updated..
        /// </summary>
        internal static string QuestCompleteLogUpdated {
            get {
                return ResourceManager.GetString("QuestCompleteLogUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient skill in {0} to undertake this quest..
        /// </summary>
        internal static string QuestDoesNotHaveRequiredSkill {
            get {
                return ResourceManager.GetString("QuestDoesNotHaveRequiredSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quest with the ID or Alias of &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string QuestNotFound {
            get {
                return ResourceManager.GetString("QuestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be in the same place as the quest giver..
        /// </summary>
        internal static string QuestNotInPlace {
            get {
                return ResourceManager.GetString("QuestNotInPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not started this quest yet..
        /// </summary>
        internal static string QuestNotStarted {
            get {
                return ResourceManager.GetString("QuestNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not undertake this quest until you complete &apos;{0}&apos;..
        /// </summary>
        internal static string QuestParentRequired {
            get {
                return ResourceManager.GetString("QuestParentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your skill in {0} has been increased to {1}..
        /// </summary>
        internal static string SkillGained {
            get {
                return ResourceManager.GetString("SkillGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were hit for {0} damage by a spell from {1}!.
        /// </summary>
        internal static string SpellDamagedByTarget {
            get {
                return ResourceManager.GetString("SpellDamagedByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell hit {0} for {1} damage!.
        /// </summary>
        internal static string SpellDamagedTarget {
            get {
                return ResourceManager.GetString("SpellDamagedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has destroyed {0}..
        /// </summary>
        internal static string SpellDestroyedTraget {
            get {
                return ResourceManager.GetString("SpellDestroyedTraget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have enchanted {0}..
        /// </summary>
        internal static string SpellEnchanted {
            get {
                return ResourceManager.GetString("SpellEnchanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has restored {0} health..
        /// </summary>
        internal static string SpellHealthGained {
            get {
                return ResourceManager.GetString("SpellHealthGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have had {0} health restored by a spell from {1}..
        /// </summary>
        internal static string SpellHealthGainedByTarget {
            get {
                return ResourceManager.GetString("SpellHealthGainedByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has restored {0} health to {1}..
        /// </summary>
        internal static string SpellHealthGainedTarget {
            get {
                return ResourceManager.GetString("SpellHealthGainedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were killed by a spell from {0}..
        /// </summary>
        internal static string SpellKilledByTarget {
            get {
                return ResourceManager.GetString("SpellKilledByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has killed {0}..
        /// </summary>
        internal static string SpellKilledTarget {
            get {
                return ResourceManager.GetString("SpellKilledTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has increased your protection by {0}..
        /// </summary>
        internal static string SpellProtectionGained {
            get {
                return ResourceManager.GetString("SpellProtectionGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your protection was increased {0} points by {1}..
        /// </summary>
        internal static string SpellProtectionGainedByTarget {
            get {
                return ResourceManager.GetString("SpellProtectionGainedByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has increased the protection of {0} by {1}..
        /// </summary>
        internal static string SpellProtectionGainedTarget {
            get {
                return ResourceManager.GetString("SpellProtectionGainedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has increased your {0} by {1}..
        /// </summary>
        internal static string SpellStatGained {
            get {
                return ResourceManager.GetString("SpellStatGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A spell from {0} has increased your {0} by {1}..
        /// </summary>
        internal static string SpellStatGainedByTarget {
            get {
                return ResourceManager.GetString("SpellStatGainedByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has increased the {0} of {1} by {2}..
        /// </summary>
        internal static string SpellStatGainedTarget {
            get {
                return ResourceManager.GetString("SpellStatGainedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been transported to {0}..
        /// </summary>
        internal static string SpellTransported {
            get {
                return ResourceManager.GetString("SpellTransported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been transported to {0}..
        /// </summary>
        internal static string SpellTransportedByTarget {
            get {
                return ResourceManager.GetString("SpellTransportedByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You transported {0} to {1}..
        /// </summary>
        internal static string SpellTransportedTarget {
            get {
                return ResourceManager.GetString("SpellTransportedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been rendered unconscious by a spell from {0}..
        /// </summary>
        internal static string SpellUnconsciousByTarget {
            get {
                return ResourceManager.GetString("SpellUnconsciousByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has rendered {0} unconscious..
        /// </summary>
        internal static string SpellUnconsciousTarget {
            get {
                return ResourceManager.GetString("SpellUnconsciousTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has restored {0} willpower..
        /// </summary>
        internal static string SpellWillpowerGained {
            get {
                return ResourceManager.GetString("SpellWillpowerGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have had your willpower restored {0} points by {1}..
        /// </summary>
        internal static string SpellWillpowerGainedByTarget {
            get {
                return ResourceManager.GetString("SpellWillpowerGainedByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell has restored {0} willpower for {1}..
        /// </summary>
        internal static string SpellWillpowerGainedTarget {
            get {
                return ResourceManager.GetString("SpellWillpowerGainedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your target is already dead..
        /// </summary>
        internal static string TargetDead {
            get {
                return ResourceManager.GetString("TargetDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already engaged with another player..
        /// </summary>
        internal static string TargetEngaged {
            get {
                return ResourceManager.GetString("TargetEngaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the target specified as &apos;{0}&apos;..
        /// </summary>
        internal static string TargetNotFound {
            get {
                return ResourceManager.GetString("TargetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not seem to be online..
        /// </summary>
        internal static string TargetNotOnline {
            get {
                return ResourceManager.GetString("TargetNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target set to {0}..
        /// </summary>
        internal static string TargetSet {
            get {
                return ResourceManager.GetString("TargetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your target is unconscious..
        /// </summary>
        internal static string TargetUnconscious {
            get {
                return ResourceManager.GetString("TargetUnconscious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Level {1} {2} {3}).
        /// </summary>
        internal static string WhoFormat {
            get {
                return ResourceManager.GetString("WhoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your willpower has increased by {0}..
        /// </summary>
        internal static string WillpowerGained {
            get {
                return ResourceManager.GetString("WillpowerGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your willpower has decreased by {0}..
        /// </summary>
        internal static string WillpowerLost {
            get {
                return ResourceManager.GetString("WillpowerLost", resourceCulture);
            }
        }
    }
}
